/**************************************************************\
Edition:
##  @date 09/10/2026 by @author Tsukini

File Name:
##  @file Core-Completion.cpp

File Description:
##  You know, I don t think there are good or bad descriptions,
##  for me, life is all about functions...
\**************************************************************/

#define _Attribute
#include <utils/utils.hpp>
#include "cluster/Core.hpp"
#include <iostream>

/* completion */
_cold void cluster::Core::completion_(void) const
{
    // Commands, flags and the session names / providers of the running instance (asked at completion time)
    const std::string commands = "list status spawn send allow mode interrupt rename cd close trash restore purge task search export remote providers notices auth serve mcp help";
    const std::string flags = "--tty --gui --backend --restore --fresh --no-global --layout --style --name --mode --profile --prompt --target --after --force --rtk --json --version --completion --help";
    const std::string sessions = "claude-cluster list --rtk 2>/dev/null | tail -n +2 | cut -d'|' -f2";
    const std::string providers = "claude-cluster auth list --rtk 2>/dev/null | cut -d'|' -f2";

    if (this->_completion == "bash") {
        std::cout << "# claude-cluster completion (bash), generated by claude-cluster --completion bash\n"
            << "_claude_cluster() {\n"
            << "    local cur=\"${COMP_WORDS[COMP_CWORD]}\" prev=\"${COMP_WORDS[COMP_CWORD-1]}\" cmd=\"${COMP_WORDS[1]}\"\n"
            << "    case \"$prev\" in\n"
            << "        --mode|-m) COMPREPLY=($(compgen -W \"default acceptEdits plan bypassPermissions\" -- \"$cur\")); return ;;\n"
            << "        --layout) COMPREPLY=($(compgen -W \"list grid tabs\" -- \"$cur\")); return ;;\n"
            << "        --completion) COMPREPLY=($(compgen -W \"bash zsh fish\" -- \"$cur\")); return ;;\n"
            << "        --backend|-b) COMPREPLY=($(compgen -W \"$(" << providers << ")\" -- \"$cur\")); return ;;\n"
            << "    esac\n"
            << "    if [[ $cur == -* ]]; then COMPREPLY=($(compgen -W \"" << flags << "\" -- \"$cur\")); return; fi\n"
            << "    if [[ $COMP_CWORD -eq 1 ]]; then COMPREPLY=($(compgen -W \"" << commands << "\" -- \"$cur\")); return; fi\n"
            << "    case \"$cmd\" in\n"
            << "        auth) if [[ $COMP_CWORD -eq 2 ]]; then COMPREPLY=($(compgen -W \"list login logout\" -- \"$cur\")); "
            << "else COMPREPLY=($(compgen -W \"$(" << providers << ")\" -- \"$cur\")); fi ;;\n"
            << "        task) COMPREPLY=($(compgen -W \"add list cancel\" -- \"$cur\")) ;;\n"
            << "        remote) COMPREPLY=($(compgen -W \"on off\" -- \"$cur\")) ;;\n"
            << "        spawn|cd) COMPREPLY=($(compgen -d -- \"$cur\")) ;;\n"
            << "        *) if [[ $COMP_CWORD -eq 2 ]]; then COMPREPLY=($(compgen -W \"$(" << sessions << ")\" -- \"$cur\")); fi ;;\n"
            << "    esac\n"
            << "}\n"
            << "complete -F _claude_cluster claude-cluster\n";
    } else if (this->_completion == "zsh") {
        std::cout << "#compdef claude-cluster\n# claude-cluster completion (zsh), generated by claude-cluster --completion zsh\n"
            << "_claude-cluster() {\n"
            << "    local -a commands sessions providers\n"
            << "    commands=(" << commands << ")\n"
            << "    if [[ $words[CURRENT] == -* ]]; then compadd -- " << flags << "; return; fi\n"
            << "    case $words[CURRENT-1] in\n"
            << "        --mode|-m) compadd default acceptEdits plan bypassPermissions; return ;;\n"
            << "        --layout) compadd list grid tabs; return ;;\n"
            << "        --completion) compadd bash zsh fish; return ;;\n"
            << "        --backend|-b) providers=(${(f)\"$(" << providers << ")\"}); compadd -a providers; return ;;\n"
            << "    esac\n"
            << "    if (( CURRENT == 2 )); then compadd -a commands; return; fi\n"
            << "    case $words[2] in\n"
            << "        auth) if (( CURRENT == 3 )); then compadd list login logout; else providers=(${(f)\"$(" << providers << ")\"}); compadd -a providers; fi ;;\n"
            << "        task) compadd add list cancel ;;\n"
            << "        remote) compadd on off ;;\n"
            << "        spawn|cd) _directories ;;\n"
            << "        *) if (( CURRENT == 3 )); then sessions=(${(f)\"$(" << sessions << ")\"}); compadd -a sessions; fi ;;\n"
            << "    esac\n"
            << "}\n"
            << "compdef _claude-cluster claude-cluster\n";
    } else if (this->_completion == "fish") {
        std::cout << "# claude-cluster completion (fish), generated by claude-cluster --completion fish\n"
            << "complete -c claude-cluster -f\n"
            << "complete -c claude-cluster -n '__fish_use_subcommand' -a '" << commands << "'\n"
            << "complete -c claude-cluster -n '__fish_seen_subcommand_from auth' -a 'list login logout'\n"
            << "complete -c claude-cluster -n '__fish_seen_subcommand_from login logout' -a '(" << providers << ")'\n"
            << "complete -c claude-cluster -n '__fish_seen_subcommand_from task' -a 'add list cancel'\n"
            << "complete -c claude-cluster -n '__fish_seen_subcommand_from remote' -a 'on off'\n"
            << "complete -c claude-cluster -n '__fish_seen_subcommand_from status send allow mode interrupt rename cd close export' -a '(" << sessions << ")'\n"
            << "complete -c claude-cluster -l mode -a 'default acceptEdits plan bypassPermissions'\n"
            << "complete -c claude-cluster -l layout -a 'list grid tabs'\n"
            << "complete -c claude-cluster -l backend -a '(" << providers << ")'\n";
        for (const char* flag: {"tty", "gui", "restore", "fresh", "no-global", "style", "name", "profile", "prompt", "target", "after", "force", "rtk", "json", "version", "help"})
            std::cout << "complete -c claude-cluster -l " << flag << "\n";
    }
}
