/**************************************************************\
Edition:
##  @date 06/10/2026 by @author Tsukini

File Name:
##  @file Core-Completion.cpp

File Description:
##  Completion scripts of xstyle (bash, zsh, fish), generated from the flags of the parser
\**************************************************************/

#define _Attribute
#define _Arguments
#include <utils/utils.hpp>
#include "xstyle/Rules.hpp"
#include "xstyle/Core.hpp"
#include <unordered_map>
#include <iostream>
#include <string>
#include <vector>

/* tools */
_cold static std::string escape_(const std::string& s, const std::string& special) // backslash before every special character
{
    std::string out;
    for (const char c: s) {
        if (special.find(c) != std::string::npos) out += '\\';
        out += c;
    }
    return out;
}

_cold static std::string short_description_(const std::string& description) // first part, without the details in parentheses
{
    std::string text = description.substr(0, description.find(" ("));
    return text.size() > 80 ? text.substr(0, 77) + "..." : text;
}

/* completion */
_cold void xstyle::Core::completion_(void) const
{
    // What each flag takes (the flags without entry take nothing)
    static const std::unordered_map<std::string, std::string> kinds = {
        {"code", "codes"}, {"ignore", "codes"}, {"explain", "codes"}, {"fix", "fix"}, {"severity", "level"}, {"fail", "level"}, {"lang", "lang"},
        {"libutils", "auto on off"}, {"format", "text md json"}, {"link", "file vscode none"}, {"completion", "bash zsh fish"}, {"report", "file"}, {"exclude", "path"},
        {"header", "none default"},
    };
    const std::string levels = "unforgivable major minor negligible";
    const std::string prefixes = "G CPP LU PY SH RS";
    std::string languages;
    for (std::uint8_t i = 0; i < static_cast<std::uint8_t>(xstyle::Language::Other); ++i)
        languages += (languages.empty() ? "" : " ") + std::string(xstyle::language_id(static_cast<xstyle::Language>(i)));
    const std::unordered_map<std::string, utils::arguments::Flag>& flags = this->_parser.getFlags();
    std::vector<std::string> ids;
    for (const auto &[title, section]: this->_sections)
        ids.insert(ids.end(), section.begin(), section.end());

    if (this->_completion == "bash") {
        std::string words = "-h --help";
        std::unordered_map<std::string, std::string> cases; // kind -> "-c|--code"
        for (const std::string& id: ids) {
            const auto &[shortName, flagName, longName, env] = flags.at(id).flag;
            const std::string names = (shortName.empty() ? "" : "-" + shortName + "|") + "--" + longName;
            words += (shortName.empty() ? "" : " -" + shortName) + " --" + longName;
            if (kinds.contains(id)) cases[kinds.at(id)] += (cases[kinds.at(id)].empty() ? "" : "|") + names;
        }
        std::cout << "# xstyle completion (bash) - generated by: xstyle --completion bash\n"
            << "_xstyle_list()\n{\n"
            << "    # Comma separated values: complete the last item, keep the others as prefix\n"
            << "    local base=\"\"\n"
            << "    [[ \"$1\" == *,* ]] && base=\"${1%,*},\"\n"
            << "    mapfile -t COMPREPLY < <(compgen -P \"$base\" -W \"$2\" -- \"${1##*,}\")\n}\n\n"
            << "_xstyle()\n{\n"
            << "    local cur=\"${COMP_WORDS[COMP_CWORD]}\" prev=\"${COMP_WORDS[COMP_CWORD - 1]}\"\n"
            << "    local codes=\"\"\n"
            << "    case \"$prev\" in\n";
        for (const auto &[kind, names]: cases) {
            std::cout << "        " << names << ")\n";
            if (kind == "codes" || kind == "fix")
                std::cout << "            codes=\"$(xstyle -L 2> /dev/null | awk 'NR > 1 {print $1}') " << prefixes << "\"\n"
                    << "            _xstyle_list \"$cur\" \"$codes\"\n"
                    << (kind == "fix" ? "            [[ \"$cur\" == [A-Z]* ]] || { compopt -o filenames; mapfile -t -O \"${#COMPREPLY[@]}\" COMPREPLY < <(compgen -f -- \"$cur\"); }\n" : "");
            else if (kind == "level") std::cout << "            mapfile -t COMPREPLY < <(compgen -W \"" << levels << "\" -- \"$cur\")\n";
            else if (kind == "lang") std::cout << "            _xstyle_list \"$cur\" \"" << languages << "\"\n";
            else if (kind == "file") std::cout << "            compopt -o filenames\n            mapfile -t COMPREPLY < <(compgen -f -- \"$cur\")\n";
            else if (kind == "path") std::cout << "            compopt -o filenames\n            mapfile -t COMPREPLY < <(compgen -d -- \"$cur\")\n";
            else std::cout << "            mapfile -t COMPREPLY < <(compgen -W \"" << kind << "\" -- \"$cur\")\n";
            std::cout << "            return\n            ;;\n";
        }
        std::cout << "    esac\n"
            << "    if [[ \"$cur\" == -* ]]; then\n"
            << "        mapfile -t COMPREPLY < <(compgen -W \"" << words << "\" -- \"$cur\")\n"
            << "        return\n    fi\n"
            << "    compopt -o filenames\n"
            << "    mapfile -t COMPREPLY < <(compgen -f -- \"$cur\")\n}\n\n"
            << "complete -F _xstyle xstyle\n";
        return;
    }

    if (this->_completion == "zsh") {
        std::cout << "#compdef xstyle\n"
            << "# xstyle completion (zsh) - generated by: xstyle --completion zsh\n\n"
            << "_xstyle_codes()\n{\n"
            << "    local -a codes\n"
            << "    codes=(${(f)\"$(xstyle -L 2> /dev/null | awk 'NR > 1 {print $1}')\"} " << prefixes << ")\n"
            << "    _sequence compadd - $codes\n}\n\n"
            << "_xstyle_langs()\n{\n"
            << "    _sequence compadd - " << languages << "\n}\n\n"
            << "_arguments -s -S \\\n"
            << "    '(- *)'{-h,--help}'[Display the help and exit]' \\\n";
        for (const std::string& id: ids) {
            const utils::arguments::Flag& flag = flags.at(id);
            const auto &[shortName, flagName, longName, env] = flag.flag;
            std::string description;
            for (const char c: escape_(short_description_(flag.description), "[]\\"))
                description += c == '\'' ? std::string("'\\''") : std::string(1, c);
            std::string spec = shortName.empty() ? "'--" + longName + "[" + description + "]"
                : "'(-" + shortName + " --" + longName + ")'{-" + shortName + ",--" + longName + "}'[" + description + "]";
            if (kinds.contains(id)) {
                const std::string kind = kinds.at(id);
                const std::string name = flag.options.empty() ? "value" : std::get<0>(flag.options[0]);
                std::string action = "(" + kind + ")";
                if (kind == "codes" || kind == "fix") action = "_xstyle_codes";
                else if (kind == "level") action = "(" + levels + ")";
                else if (kind == "lang") action = "_xstyle_langs";
                else if (kind == "file") action = "_files";
                else if (kind == "path") action = "_files -/";
                spec += (kind == "fix" ? "::" : ":") + name + ":" + action;
            }
            std::cout << "    " << spec << "' \\\n";
        }
        std::cout << "    '*:path:_files'\n";
        return;
    }

    // fish
    std::cout << "# xstyle completion (fish) - generated by: xstyle --completion fish\n"
        << "function __xstyle_codes\n"
        << "    xstyle -L 2> /dev/null | awk 'NR > 1 {print $1}'\n"
        << "    printf '%s\\n' " << prefixes << "\n"
        << "end\n\n"
        << "complete -c xstyle -s h -l help -d 'Display the help and exit'\n";
    for (const std::string& id: ids) {
        const utils::arguments::Flag& flag = flags.at(id);
        const auto &[shortName, flagName, longName, env] = flag.flag;
        std::cout << "complete -c xstyle" << (shortName.empty() ? "" : " -s " + shortName) << " -l " << longName;
        if (kinds.contains(id)) {
            const std::string kind = kinds.at(id);
            if (kind == "codes") std::cout << " -x -a '(__xstyle_codes)'";
            else if (kind == "fix") std::cout << " -a '(__xstyle_codes)'";
            else if (kind == "level") std::cout << " -x -a '" << levels << "'";
            else if (kind == "lang") std::cout << " -x -a '" << languages << "'";
            else if (kind == "file" || kind == "path") std::cout << " -r -F";
            else std::cout << " -x -a '" << kind << "'";
        }
        std::cout << " -d '" << escape_(short_description_(flag.description), "'\\") << "'\n";
    }
}
