[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{{NAME}}"
dynamic = ["version"]
description = "{{DESC}}"
readme = "README.md"
license = "MIT"
authors = [{ name = "Tsukini" }]
requires-python = ">={{PYTHON}}"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
{{NAME}} = "{{PACKAGE}}.main:main"

[tool.setuptools.dynamic]
version = { attr = "{{PACKAGE}}.const.VERSION" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
